version: '3'
services:
  json-server:
    image: node
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    working_dir: /app
    command: sh -c "npm install -g json-server && json-server --watch data/db.json --host 0.0.0.0"

