version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/app/static:ro
    depends_on:
      - lite-server
      - json-server
  
  lite-server:
    image: node
    ports:
      - "8080-8083:8080"
    volumes:
      - ./static:/app/static
      - ./bs-config.json:/app/bs-config.json
    working_dir: /app
    command: sh -c "npm install -g lite-server && lite-server --config bs-config.json --no-open"
    tty: true

  json-server:
    image: node
    volumes:
      - ./data:/app/data
    working_dir: /app
    command: sh -c "npm install -g json-server && json-server --watch data/db.json --host 0.0.0.0"

